### ISSUE TITLE
Active Nav toggles at wrong place when offset is negative

### ISSUE THREAD

**Issue by JonathanXu1** [StephenWeiXu/react-scrollspy-nav#12]
First of all, thanks for this simple tool, it has been very useful!
The main issue I'm having is this:

When the offset is negative, the corresponding nav links are highlighted as if the offset was set to the absolute value of the negative value.

I have to set the offset to negative to get the scrollspy to scroll to the proper location, so I haven't found a way around this bug just yet.

**Comment by stoodkev** [comment]
same here @StephenWeiXu. Hope you can help =)

**Comment by StephenWeiXu** [comment]
@stoodkev thanks for the PR. Code change looks good to me. PR merged
