### ISSUE TITLE
Issue with release@1.2.3

### ISSUE THREAD

**Issue by rackstar17** [StephenWeiXu/react-scrollspy-nav#18]
I got the following error while making the frontend build - 

ReferenceError: window is not defined
--
561 | at Object.<anonymous> (/usr/src/app/node_modules/react-scrollspy-nav/dist/ScrollspyNav.js:1:286)

We're using react(15.6.2), react-dom(16.13.0)
Is it a backwards compatibility issue ?

I was previously using version 1.2.1 and it worked fine.

**Comment by StephenWeiXu** [comment]
@rackstar17  Thanks for bringing it up. Looking into it

**Comment by StephenWeiXu** [comment]
@rackstar17 Please trying upgrading react version to 16 and try it again.

You might see a general warning about react and react-dom version(see below) as well when you do `npm install` in your package.

```
npm WARN react-dom@16.13.0 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
```
