### ISSUE TITLE
Wishlist: Offset parameter

### ISSUE THREAD

**Issue by thebarty** [StephenWeiXu/react-scrollspy-nav#2]
Hi,

this works great, BUT could really need an offset parameter like in https://www.npmjs.com/package/react-scrollspy.

**Comment by StephenWeiXu** [comment]
Hi there, offset parameter is added in the latest release https://github.com/StephenWeiXu/react-scrollspy-nav/releases/tag/v1.2.2, referring to PR here #6. Thanks for your suggestion!
