### ISSUE TITLE
typeof window

### ISSUE THREAD

**Issue by jacuna565** [StephenWeiXu/react-scrollspy-nav#34]
You should verificate with "typeof window" whenever you use "window" variable. This could cause problems with server side rendering.

I'm using Gatsby and i can not use it because of that

please just add typeof window variable verification :)

**Comment by StephenWeiXu** [comment]
Thanks for bringing this up. You are more than welcome to open a pull request for this feature.

**Comment by StephenWeiXu** [comment]
Resolved it new release https://www.npmjs.com/package/react-scrollspy-nav/v/1.3.0
