### ISSUE TITLE
Uncaught TypeError: Cannot read property 'offsetTop' of null

### ISSUE THREAD

**Issue by Pisik8809** [StephenWeiXu/react-scrollspy-nav#5]
Hi, i have routing in my app, but if i haven't nav or sections on interest in target URL i got this in console.
Uncaught TypeError: Cannot read property 'offsetTop' of null
Uncaught TypeError: Cannot read property 'scrollHeight' of null
I try write some check in block [
 var t;
          e.scrollTargetIds.map(function (n, r) {
            t = document.getElementById(n); if(t){t.offsetTop - (e.headerBackground ? document.querySelector("div[data-nav='list']").scrollHeight : 0), window.pageYOffset >= t && window.pageYOffset < t + document.getElementById(n).scrollHeight ? (e.getNavLinkElement(n).classList.add(e.activeNavClass), e.clearOtherNavLinkActiveStyle(n)) : e.getNavLinkElement(n).classList.remove(e.activeNavClass), window.innerHeight + window.pageYOffset >= document.body.scrollHeight && r === e.scrollTargetIds.length - 1 && (e.getNavLinkElement(n).classList.add(e.activeNavClass), e.clearOtherNavLinkActiveStyle(n))};
          });
        });
]
but in that case spy not working like spy, not highlight on scroll.
Can u seggest some solution?

**Comment by aliaanis** [comment]
I am facing the same issue, any solution yet?

**Comment by Pisik8809** [comment]
> I am facing the same issue, any solution yet?

i use another package "react-scroll"
https://github.com/fisshy/react-scroll
